export default types = {

    RETRIEVE_TOKEN: 'RETRIEVE_TOKEN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    REFRESHING_TOKEN: 'REFRESHING_TOKEN',
    LOGOUT: 'LOGOUT',
    USER_DETAILS: 'USER_DETAILS',




}